version: "3"
services:
  database:
    container_name: ${DB_CONTAINER}
    image: ${COMPOSE_PROJECT_NAME}/${DB_CONTAINER}
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    networks:
      - default
    environment:
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb_root_password
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongodb_root_username
      MONGO_USERNAME_FILE: /run/secrets/mongodb_username
      MONGO_PASSWORD_FILE: /run/secrets/mongodb_password
      MONGO_INITDB_DATABASE: admin
      MONGO_DATABASE: appDb
    secrets:
      - mongodb_root_password
      - mongodb_root_username
      - mongodb_password
      - mongodb_username

  server:
    container_name: ${SERVER_CONTAINER}
    image: ${COMPOSE_PROJECT_NAME}/${SERVER_CONTAINER}
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - default
    environment:
      MONGODB_HOSTNAME: ${DB_CONTAINER}

  client:
    container_name: ${CLIENT_CONTAINER}
    image: ${COMPOSE_PROJECT_NAME}/${CLIENT_CONTAINER}
    build:
      context: ./client
    ports:
      - "3000:80"
    networks:
      - default

networks:
  default:

secrets:
  mongodb_root_password:
    file: ./database/config/.mongodb_root_password
  mongodb_root_username:
    file: ./database/config/.mongodb_root_username
  mongodb_password:
    file: ./database/config/.mongodb_password
  mongodb_username:
    file: ./database/config/.mongodb_username
